### ISSUE TITLE
Publish to npm on GitHub release

### ISSUE THREAD

**Issue by ivov** [ivov/eslint-plugin-n8n-nodes-base#102]
```yml
name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out commit
        uses: actions/checkout@v3
     
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install, build, publish
        run: |
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
